### ISSUE TITLE
Vereinszweck

### ISSUE THREAD

**Issue by behrmann** [ZaPF/Satzung_des_ZaPFev#2]
Es gibt einen Vorschlag für eine konformere Formulierung. Es müssen alle Vereinsmitglieder zustimmen.

**Comment by scattenlaeufer** [comment]
Hier eine Hilfestellung zur Erhaltung der Gemeinnützigkeit:

- https://deutsches-ehrenamt.de/vereinsrecht/gemeinnuetzigkeit-verein/

**Comment by psteinmu** [comment]
Der Vorschlag lautet wie folgt:
§ 2 Zweck des Vereins
    1. Der Verein dient der Förderung von Wissenschaft und Forschung, sowie des demokratischen Staatswesen.
    2. Der Satzungszweck wird insbesondere verwirklicht durch:
        (a) die Durchführung der halbjährlichen Treffen der Vertretenden der Physikstudierenden der Hochschulen im deutschsprachigen Raum, der Zusammenkunft aller Physikfachschaften (ZaPF).
        (b) die Umsetzung und Finanzierung der Beschlüsse der ZaPF, sowie deren Gremien.

Der Verein bezweckt mit diesen Aufgaben einen Informationsaustausch der einzelnen Studierendenvertretungen und soll so eine überregionale Koordination ermöglichen. Durch Fachvorträge soll über neueste Entwicklungen aus Wissenschaft, Forschung und Technologie berichtet werden.
