### ISSUE TITLE
Sitz des Vereins

### ISSUE THREAD

**Issue by scattenlaeufer** [ZaPF/Satzung_des_ZaPFev#3]
Aktuell ist des Sitz des Vereins die Fachschaft in Frankfurt. Das hat auch lange gut funktioniert und Fachschaftika haben immer die Post des Vereins sehr gut verwaltet. Da aktuell aber keine Fachschaftika aus Frankfurt im Vorstand des ZaPF e.V. sind, ist das eine problematische Situation.

Da der Wechsel des Sitzes eines Vereins sehr aufwendig ist, muss ein Weg gefunden werden, wie der Sitz des Vereins und seine Postanschrift getrennt werden.

**Comment by psteinmu** [comment]
Unter https://npo-experten.de/de/npo-wissen/vereinsgruendung/vereinssitz-bestimmen/ steht:

- Der Verein muss einen Satzungssitz innerhalb der Bundesrepublik Deutschland wählen.
-  Eine postalische Erreichbarkeit muss gegeben sein, wenn nicht am Satzungssitz des Vereins, so muss doch zumindest dem Registergericht eine ladungsfähige Anschrift in Deutschland mitgeteilt werden.
- Es muss der Bestimmtheitsgrundsatz beachtet werden, d. h. der Satzungssitz muss sich an einem eindeutig zuordenbaren Ort befinden. Regelmäßig wird hier eine politische Gemeinde gewählt.
- Der Verein kann nur einen Satzungssitz haben. Dies gilt auch bei Verschmelzung zweier Vereine oder Ausdehnung der Organisation auf Gebiete außerhalb des Sitzes.

Die Frage, wie dies in der Satzung zu regeln ist, kläre ich mit der Rechtsberatung des Deutschen Ehrenamtes.

**Comment by niklasjam** [comment]
In der Satzung ist Frankfurt als Vereinssitz angegeben. Mittelfristig erscheint eine Änderung nicht notwendig.
